spring.application.name=Able Care Mobile Therapy

# Database Connection URL (Change 'ablecare' if you name your database differently)
#spring.datasource.url=jdbc:postgresql://localhost:5432/ablecare

# PostgreSQL Credentials (replace with your actual local username and password)
#spring.datasource.username=postgres
#spring.datasource.password=

# Specify the PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Ensure Spring Boot manages the lifecycle of the container
spring.docker.compose.lifecycle-management=start-and-stop


# The Auto-Generation Magic (creates/updates tables based on your Java entities)
spring.jpa.hibernate.ddl-auto=create

# Optional: Show SQL in the console (great for debugging while prototyping)
spring.jpa.show-sql=true